### PR TITLE
Add support for BeagleBone AI

### PR DESCRIPTION
**Pull request by DhruvaG2000**
This PR aims to add support for the BeagleBone AI running `Linux beaglebone 4.19.94-ti-xenomai-r64`
**NOTE** The necessary BELA Cape overlay for BeagleBone AI can be found here: [BBAI-BELA-00A1.dts](https://github.com/DhruvaG2000/BeagleBoard-DeviceTrees/blob/v4.19.x-ti-overlays/src/arm/overlays/BBAI-BELA-00A1.dts) 

## Feature List:
- Creation of PruManager which helps migrate to using the _remote processor framework_ on newe kernels while also maintaining backward compatibility for `libprussdrv` on the Am335x.
- New workflow for building the PRU code with clpru. (Which has been integrated in the Makefile)
- The core as well as PRU codes now decide at compile time depending on which board they are running on, which base constants are to be used by the code.
- Add McASP configuration that works on AM572x.
- Add GPIO support for AM572x.
- Add SPI support for AM572x

### CODE REVIEW

**Comment by znmeb** [comment]
Cool! Will assembled units be coming with the BeagleBone AI?

**Comment by DhruvaG2000** [comment]
@znmeb There are still some major limitations to using BELA on the BBAI, to name a few:

- Xenomai patched kernel (`Linux beaglebone 4.19.94-ti-xenomai-r64`) crash on boot, and the board needs to be reset a couple of times to properly boot.
- The interrupts in AM572x turned out to be much complicated than AM335x due to a new concept called `IRQ_CROSSBARS` which me and the Bela team have been working on for a few days. This may take some more time to implements.
- Thus, to get a proper release of BELA image for the BBAI, we really need to get the first issue of kernel crashing resolved, which again will take time.

So, at the current stage, the only option is to manually update to the xenomai patched kernel x4.19 using one of the on-board scripts, and then one can source compile BELA using some basic instructions that I have provided on [my blog](https://dhruvag2000.github.io/Blog-GSoC21/Bela/source-compile.html).

**Comment by znmeb** [comment]
Thanks! I'm not in any great hurry - I have two Belas running just fine without hitting any hardware limits. I can wait for assembled units.

**Comment by giuliomoro** [comment]
@DhruvaG2000 thanks for this, please make a new PR against the `dev-next` branch.

**Pull request closed without merging**
