### PR TITLE
Merging changes for Eclipse project

### PR DESCRIPTION
**Pull request by AndrewCapon**
Merging changes for Eclipse project

### CODE REVIEW

**Comment by giuliomoro** [comment]
right that didn't go down so well. I think that may have to do with:
- your `dev` branch being very old
- some confusion we made on our own `dev` last summer, when we merged some CTAG stuff in.
- among the commits list above, there are some `dev-modular` stuff

I would suggest you:
- re-checkout the `dev` branch from our repo (optionally rename it so you do not have to delete your own `dev`. However you most likely want to delete your own `dev`, because it's a bit messy, judging from the above)
- apply your commits on top of that (you can `git cherry-pick 
a143f68` , `git cherry-pick 8cf761d`, `git cherry-pick 6e3e0e4`, `git cherry-pick 98d16db` )
- push again
- create a new merge request

**Comment by AndrewCapon** [comment]
I originally used the dev-modular branch.

I checked out the dev branch today and merged the dev-modular to the dev branch using git and then pushed it to github.

I’m a bit confused how the dev branch was out of data but then again I have got history of messing up source control systems!

I’ll see what mess I can get into ...

**Comment by giuliomoro** [comment]
Oh ok then perhaps the only confusion is due to the fact that you merged in `dev-modular`. I'd suggest you start from scratch, apply your changes on `dev` and create a pull-request for that. Then I will merge `dev` into `dev-modular` and you can keep tracking our own `dev-modular`

**Comment by AndrewCapon** [comment]
sounds like a good plan. I have a beer poured now, I’m guessing that will help...

**Comment by AndrewCapon** [comment]
went better this time, I also had to pull before pushing after switching to dev branch. Didn't get that last time.

**Pull request closed without merging**
